***NumPy***

O NumPy (Numerical Python) é uma biblioteca open source em
Python, largamente utilizada em quase todos os campos da
ciência
e engenharia

CRIANDO UM NUMPY ARRAY






In [4]:
import numpy as np

#CRIANDO UM NUMPY ARRAY 1D
arr = np.array([10,20,30,40,50,60])
print(arr)
print(type(arr))

#PROPRIEDADES DO ARRAY
print(arr.size) #quantidade de elementos
print(arr.ndim) #numero de dimensão
print(arr.shape) #formato do array

mtz = np.array(([10,20], [30,40], [50,60]))
print(mtz)
#PROPRIEDADES DO ARRAY
print(mtz.size)
print(mtz.ndim)
print(mtz.shape)

[10 20 30 40 50 60]
<class 'numpy.ndarray'>
6
1
(6,)
[[10 20]
 [30 40]
 [50 60]]
6
2
(3, 2)


FUNÇÕES PRÉ-PRONTAS PARA ESTRUTURARMOS UM NUMPY ARRAYS

In [9]:
#Ones
# cria um array uni ou bidimensional formado por 1`s
mtz = np.ones([5, 5])
print(mtz)

#zeros
# cria um array uni ou bidimensional formado por 0`s
arr = np.zeros(10)
print(arr.reshape(5,2)) #transforma um vetor em uma matriz

#Arange
# cria um array unidimensional formado por elementos espaçados
mtz = np.arange(2, 21, 2) #mostra a abrangência e o primeiro é  inclusivo e o segundo exclusivo
print(mtz.reshape(2,5))



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


OPERAÇÕES ENTRE NUMPY ARRAYS

In [14]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([60,40,20,10,5])
arr3 = arr1 + arr2

#Operações entre Arrays
print(arr3)
print(arr1 - arr2)
print(arr1 * arr2)

#Concatenação de Arrays
arr3 = np.concatenate([arr1, arr2])
print(arr3)

#Broadcasting - quando um ESCALAR faz uma operação com um ARRAY
print(5 * arr3)

[70 60 50 50 55]
[-50 -20  10  30  45]
[600 800 600 400 250]
[10 20 30 40 50 60 40 20 10  5]
[ 50 100 150 200 250 300 200 100  50  25]


In [23]:
#ESTRUTURANDO UMA MATRIZ COM CONTAS
mtz = np.arange(10, 96, 5)
mtz = mtz.reshape(3, 6)
print(mtz)

#EXTRAINDO A MATRIZ DA PRIMEIRA COLUNA (NET)
print(mtz.sum(axis=0))
print(mtz.sum(axis=0)[0]) # Eixo 0 = coluna

print(mtz.sum(axis=1)) # Eixo 1 = linha
print(mtz.sum(axis=1)[1])

[[10 15 20 25 30 35]
 [40 45 50 55 60 65]
 [70 75 80 85 90 95]]
[120 135 150 165 180 195]
120
[135 315 495]
315


NÚMEROS ALEATÓRIOS NO NUMPY (MÓDULO RANDOM)

In [29]:
#PLANTANDO A SEMENTE ALEATÓRIA
np.random.seed(5)
arr = np.random.randint(1, 10, 10)
print(arr)

#EXTRAINDO ELEMENTOS ÚNICOS
print(np.unique(arr))

#CONTANDO ELEMENTOS ÚNICOS
print(np.unique(arr, return_counts=True))

[4 7 7 1 9 5 8 1 1 8]
[1 4 5 7 8 9]
(array([1, 4, 5, 7, 8, 9]), array([3, 1, 1, 2, 2, 1]))
